version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: keycloak_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - keycloak_network

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak_service
    restart: unless-stopped
    environment:
      # CAMBIO AQUÍ: Nuevas variables obligatorias en Keycloak 26
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      
      # Lo demás se mantiene igual
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_PROXY_HEADERS: xforwarded 
      KC_HTTP_ENABLED: 'true'
    ports:
      - "${KC_PORT}:8080"
    volumes:
      - ./data/keycloak_providers:/opt/keycloak/providers
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - keycloak_network

networks:
  keycloak_network:
    driver: bridge
