parent=base
name=RNI Theme
styles=resources/style.css 

# --- Clases CSS personalizadas ---
kcHtmlClass=
kcBodyClass=login-body
kcLoginClass=login-container
kcHeaderClass=login-header
kcHeaderWrapperClass=login-header-wrapper
kcFormCardClass=login-card
kcFormHeaderClass=login-form-header
kcFormGroupClass=form-group
kcLabelWrapperClass=
kcLabelClass=form-label
kcInputWrapperClass=
kcInputClass=form-input
kcButtonClass=btn
kcButtonPrimaryClass=btn-primary
kcButtonBlockClass=btn-block
kcButtonLargeClass=btn-lg
kcFormOptionsClass=form-options
kcFormOptionsWrapperClass=
kcFormButtonsClass=form-buttons
kcInputErrorMessageClass=error-message
kcAlertClass=alert
kcAlertTitleClass=alert-title
kcSignUpClass=info-area
kcInfoAreaWrapperClass=info-wrapper